project:
  type: website
  output-dir: docs

website:
  title: "Bauhaus Biografien"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - A.qmd
      - B.qmd
      - C.qmd
      - D.qmd
      - E.qmd
      - F.qmd
      - G.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



